/*
  This file will be overwritten by wxDev-C++ at every compile.
  Do not edit this file as your changes will be lost.
  You can, however, include this file and use the defines.
*/
#ifndef MACSVR_PRIVATE_H
#define MACSVR_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"1.4.0.105"
#define VER_MAJOR	1
#define VER_MINOR	4
#define VER_RELEASE	0
#define VER_BUILD	105
#define COMPANY_NAME	"T-ware Inc."
#define FILE_VERSION	"1.4"
#define FILE_DESCRIPTION	"Recieve MAC Address From Tablet Client"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	"(c) Tody 2012, T-ware Inc."
#define LEGAL_TRADEMARKS	"(c) T-ware"
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	"MAC Recieve Server"
#define PRODUCT_VERSION	"1.4"

#endif /*MACSVR_PRIVATE_H*/
